// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: arena.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArenaConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Width              float32                `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`
	Height             float32                `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	Obstacles          []*Obstacle            `protobuf:"bytes,5,rep,name=obstacles,proto3" json:"obstacles,omitempty"`
	Zones              []*Zone                `protobuf:"bytes,6,rep,name=zones,proto3" json:"zones,omitempty"`
	MaxBots            int32                  `protobuf:"varint,7,opt,name=max_bots,json=maxBots,proto3" json:"max_bots,omitempty"`
	MatchDurationTicks int64                  `protobuf:"varint,8,opt,name=match_duration_ticks,json=matchDurationTicks,proto3" json:"match_duration_ticks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArenaConfig) Reset() {
	*x = ArenaConfig{}
	mi := &file_arena_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaConfig) ProtoMessage() {}

func (x *ArenaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaConfig.ProtoReflect.Descriptor instead.
func (*ArenaConfig) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{0}
}

func (x *ArenaConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArenaConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArenaConfig) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ArenaConfig) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ArenaConfig) GetObstacles() []*Obstacle {
	if x != nil {
		return x.Obstacles
	}
	return nil
}

func (x *ArenaConfig) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *ArenaConfig) GetMaxBots() int32 {
	if x != nil {
		return x.MaxBots
	}
	return 0
}

func (x *ArenaConfig) GetMatchDurationTicks() int64 {
	if x != nil {
		return x.MatchDurationTicks
	}
	return 0
}

type Obstacle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position       *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Radius         float32                `protobuf:"fixed32,3,opt,name=radius,proto3" json:"radius,omitempty"` // All obstacles are circular in v1
	Indestructible bool                   `protobuf:"varint,4,opt,name=indestructible,proto3" json:"indestructible,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Obstacle) Reset() {
	*x = Obstacle{}
	mi := &file_arena_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obstacle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obstacle) ProtoMessage() {}

func (x *Obstacle) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obstacle.ProtoReflect.Descriptor instead.
func (*Obstacle) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{1}
}

func (x *Obstacle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Obstacle) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Obstacle) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Obstacle) GetIndestructible() bool {
	if x != nil {
		return x.Indestructible
	}
	return false
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Radius        float32                `protobuf:"fixed32,3,opt,name=radius,proto3" json:"radius,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // HEAL, ENERGY, HAZARD
	Intensity     float32                `protobuf:"fixed32,5,opt,name=intensity,proto3" json:"intensity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_arena_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{2}
}

func (x *Zone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Zone) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Zone) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Zone) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Zone) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

type ReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	StartTick     int64                  `protobuf:"varint,2,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"`
	EndTick       int64                  `protobuf:"varint,3,opt,name=end_tick,json=endTick,proto3" json:"end_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_arena_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{3}
}

func (x *ReplayRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ReplayRequest) GetStartTick() int64 {
	if x != nil {
		return x.StartTick
	}
	return 0
}

func (x *ReplayRequest) GetEndTick() int64 {
	if x != nil {
		return x.EndTick
	}
	return 0
}

type ReplayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Events        []*SimulationEvent     `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayData) Reset() {
	*x = ReplayData{}
	mi := &file_arena_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayData) ProtoMessage() {}

func (x *ReplayData) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayData.ProtoReflect.Descriptor instead.
func (*ReplayData) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{4}
}

func (x *ReplayData) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ReplayData) GetEvents() []*SimulationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type HighlightMoment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // DEATH, KILL, DAMAGE
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighlightMoment) Reset() {
	*x = HighlightMoment{}
	mi := &file_arena_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighlightMoment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighlightMoment) ProtoMessage() {}

func (x *HighlightMoment) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighlightMoment.ProtoReflect.Descriptor instead.
func (*HighlightMoment) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{5}
}

func (x *HighlightMoment) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *HighlightMoment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HighlightMoment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type HighlightsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Moments       []*HighlightMoment     `protobuf:"bytes,2,rep,name=moments,proto3" json:"moments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighlightsData) Reset() {
	*x = HighlightsData{}
	mi := &file_arena_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighlightsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighlightsData) ProtoMessage() {}

func (x *HighlightsData) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighlightsData.ProtoReflect.Descriptor instead.
func (*HighlightsData) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{6}
}

func (x *HighlightsData) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *HighlightsData) GetMoments() []*HighlightMoment {
	if x != nil {
		return x.Moments
	}
	return nil
}

type RegisterBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	SourceCode    string                 `protobuf:"bytes,4,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"` // Base64 encoded or raw string for v1
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBotRequest) Reset() {
	*x = RegisterBotRequest{}
	mi := &file_arena_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBotRequest) ProtoMessage() {}

func (x *RegisterBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBotRequest.ProtoReflect.Descriptor instead.
func (*RegisterBotRequest) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterBotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterBotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterBotRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterBotRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *RegisterBotRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type RegisterBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBotResponse) Reset() {
	*x = RegisterBotResponse{}
	mi := &file_arena_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBotResponse) ProtoMessage() {}

func (x *RegisterBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBotResponse.ProtoReflect.Descriptor instead.
func (*RegisterBotResponse) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterBotResponse) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *RegisterBotResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *RegisterBotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterBotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_arena_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{9}
}

func (x *MatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Status        MatchStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=codearena.v1.MatchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_arena_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{10}
}

func (x *MatchResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResponse) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

type MatchList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*MatchResponse       `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchList) Reset() {
	*x = MatchList{}
	mi := &file_arena_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchList) ProtoMessage() {}

func (x *MatchList) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchList.ProtoReflect.Descriptor instead.
func (*MatchList) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{11}
}

func (x *MatchList) GetMatches() []*MatchResponse {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_arena_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{12}
}

type StopSimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSimulationRequest) Reset() {
	*x = StopSimulationRequest{}
	mi := &file_arena_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSimulationRequest) ProtoMessage() {}

func (x *StopSimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSimulationRequest.ProtoReflect.Descriptor instead.
func (*StopSimulationRequest) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{13}
}

func (x *StopSimulationRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type SimulationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MatchStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=codearena.v1.MatchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationResponse) Reset() {
	*x = SimulationResponse{}
	mi := &file_arena_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResponse) ProtoMessage() {}

func (x *SimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arena_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResponse.ProtoReflect.Descriptor instead.
func (*SimulationResponse) Descriptor() ([]byte, []int) {
	return file_arena_proto_rawDescGZIP(), []int{14}
}

func (x *SimulationResponse) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

var File_arena_proto protoreflect.FileDescriptor

const file_arena_proto_rawDesc = "" +
	"\n" +
	"\varena.proto\x12\fcodearena.v1\x1a\rbot_api.proto\"\x8c\x02\n" +
	"\vArenaConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\x124\n" +
	"\tobstacles\x18\x05 \x03(\v2\x16.codearena.v1.ObstacleR\tobstacles\x12(\n" +
	"\x05zones\x18\x06 \x03(\v2\x12.codearena.v1.ZoneR\x05zones\x12\x19\n" +
	"\bmax_bots\x18\a \x01(\x05R\amaxBots\x120\n" +
	"\x14match_duration_ticks\x18\b \x01(\x03R\x12matchDurationTicks\"\x8d\x01\n" +
	"\bObstacle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.codearena.v1.Vector3R\bposition\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x02R\x06radius\x12&\n" +
	"\x0eindestructible\x18\x04 \x01(\bR\x0eindestructible\"\x93\x01\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.codearena.v1.Vector3R\bposition\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x02R\x06radius\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\tintensity\x18\x05 \x01(\x02R\tintensity\"d\n" +
	"\rReplayRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"start_tick\x18\x02 \x01(\x03R\tstartTick\x12\x19\n" +
	"\bend_tick\x18\x03 \x01(\x03R\aendTick\"^\n" +
	"\n" +
	"ReplayData\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x125\n" +
	"\x06events\x18\x02 \x03(\v2\x1d.codearena.v1.SimulationEventR\x06events\"[\n" +
	"\x0fHighlightMoment\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"d\n" +
	"\x0eHighlightsData\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x127\n" +
	"\amoments\x18\x02 \x03(\v2\x1d.codearena.v1.HighlightMomentR\amoments\"\x98\x01\n" +
	"\x12RegisterBotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vsource_code\x18\x04 \x01(\tR\n" +
	"sourceCode\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"\x7f\n" +
	"\x13RegisterBotResponse\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\")\n" +
	"\fMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"]\n" +
	"\rMatchResponse\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\tR\amatchId\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.codearena.v1.MatchStatusR\x06status\"B\n" +
	"\tMatchList\x125\n" +
	"\amatches\x18\x01 \x03(\v2\x1b.codearena.v1.MatchResponseR\amatches\"\a\n" +
	"\x05Empty\"2\n" +
	"\x15StopSimulationRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"G\n" +
	"\x12SimulationResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.codearena.v1.MatchStatusR\x06status2\x89\x04\n" +
	"\fMatchService\x12E\n" +
	"\vCreateMatch\x12\x19.codearena.v1.ArenaConfig\x1a\x1b.codearena.v1.MatchResponse\x12A\n" +
	"\x11ListActiveMatches\x12\x13.codearena.v1.Empty\x1a\x17.codearena.v1.MatchList\x12;\n" +
	"\vListMatches\x12\x13.codearena.v1.Empty\x1a\x17.codearena.v1.MatchList\x12D\n" +
	"\n" +
	"WatchMatch\x12\x1a.codearena.v1.MatchRequest\x1a\x18.codearena.v1.WorldState0\x01\x12R\n" +
	"\vRegisterBot\x12 .codearena.v1.RegisterBotRequest\x1a!.codearena.v1.RegisterBotResponse\x12G\n" +
	"\x0eGetMatchReplay\x12\x1b.codearena.v1.ReplayRequest\x1a\x18.codearena.v1.ReplayData\x12O\n" +
	"\x12GetMatchHighlights\x12\x1b.codearena.v1.ReplayRequest\x1a\x1c.codearena.v1.HighlightsData2\xbc\x01\n" +
	"\x11SimulationService\x12N\n" +
	"\x0fStartSimulation\x12\x19.codearena.v1.ArenaConfig\x1a .codearena.v1.SimulationResponse\x12W\n" +
	"\x0eStopSimulation\x12#.codearena.v1.StopSimulationRequest\x1a .codearena.v1.SimulationResponseB9Z7github.com/codearena-platform/codearena-core/pkg/api/v1b\x06proto3"

var (
	file_arena_proto_rawDescOnce sync.Once
	file_arena_proto_rawDescData []byte
)

func file_arena_proto_rawDescGZIP() []byte {
	file_arena_proto_rawDescOnce.Do(func() {
		file_arena_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arena_proto_rawDesc), len(file_arena_proto_rawDesc)))
	})
	return file_arena_proto_rawDescData
}

var file_arena_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_arena_proto_goTypes = []any{
	(*ArenaConfig)(nil),           // 0: codearena.v1.ArenaConfig
	(*Obstacle)(nil),              // 1: codearena.v1.Obstacle
	(*Zone)(nil),                  // 2: codearena.v1.Zone
	(*ReplayRequest)(nil),         // 3: codearena.v1.ReplayRequest
	(*ReplayData)(nil),            // 4: codearena.v1.ReplayData
	(*HighlightMoment)(nil),       // 5: codearena.v1.HighlightMoment
	(*HighlightsData)(nil),        // 6: codearena.v1.HighlightsData
	(*RegisterBotRequest)(nil),    // 7: codearena.v1.RegisterBotRequest
	(*RegisterBotResponse)(nil),   // 8: codearena.v1.RegisterBotResponse
	(*MatchRequest)(nil),          // 9: codearena.v1.MatchRequest
	(*MatchResponse)(nil),         // 10: codearena.v1.MatchResponse
	(*MatchList)(nil),             // 11: codearena.v1.MatchList
	(*Empty)(nil),                 // 12: codearena.v1.Empty
	(*StopSimulationRequest)(nil), // 13: codearena.v1.StopSimulationRequest
	(*SimulationResponse)(nil),    // 14: codearena.v1.SimulationResponse
	(*Vector3)(nil),               // 15: codearena.v1.Vector3
	(*SimulationEvent)(nil),       // 16: codearena.v1.SimulationEvent
	(MatchStatus)(0),              // 17: codearena.v1.MatchStatus
	(*WorldState)(nil),            // 18: codearena.v1.WorldState
}
var file_arena_proto_depIdxs = []int32{
	1,  // 0: codearena.v1.ArenaConfig.obstacles:type_name -> codearena.v1.Obstacle
	2,  // 1: codearena.v1.ArenaConfig.zones:type_name -> codearena.v1.Zone
	15, // 2: codearena.v1.Obstacle.position:type_name -> codearena.v1.Vector3
	15, // 3: codearena.v1.Zone.position:type_name -> codearena.v1.Vector3
	16, // 4: codearena.v1.ReplayData.events:type_name -> codearena.v1.SimulationEvent
	5,  // 5: codearena.v1.HighlightsData.moments:type_name -> codearena.v1.HighlightMoment
	17, // 6: codearena.v1.MatchResponse.status:type_name -> codearena.v1.MatchStatus
	10, // 7: codearena.v1.MatchList.matches:type_name -> codearena.v1.MatchResponse
	17, // 8: codearena.v1.SimulationResponse.status:type_name -> codearena.v1.MatchStatus
	0,  // 9: codearena.v1.MatchService.CreateMatch:input_type -> codearena.v1.ArenaConfig
	12, // 10: codearena.v1.MatchService.ListActiveMatches:input_type -> codearena.v1.Empty
	12, // 11: codearena.v1.MatchService.ListMatches:input_type -> codearena.v1.Empty
	9,  // 12: codearena.v1.MatchService.WatchMatch:input_type -> codearena.v1.MatchRequest
	7,  // 13: codearena.v1.MatchService.RegisterBot:input_type -> codearena.v1.RegisterBotRequest
	3,  // 14: codearena.v1.MatchService.GetMatchReplay:input_type -> codearena.v1.ReplayRequest
	3,  // 15: codearena.v1.MatchService.GetMatchHighlights:input_type -> codearena.v1.ReplayRequest
	0,  // 16: codearena.v1.SimulationService.StartSimulation:input_type -> codearena.v1.ArenaConfig
	13, // 17: codearena.v1.SimulationService.StopSimulation:input_type -> codearena.v1.StopSimulationRequest
	10, // 18: codearena.v1.MatchService.CreateMatch:output_type -> codearena.v1.MatchResponse
	11, // 19: codearena.v1.MatchService.ListActiveMatches:output_type -> codearena.v1.MatchList
	11, // 20: codearena.v1.MatchService.ListMatches:output_type -> codearena.v1.MatchList
	18, // 21: codearena.v1.MatchService.WatchMatch:output_type -> codearena.v1.WorldState
	8,  // 22: codearena.v1.MatchService.RegisterBot:output_type -> codearena.v1.RegisterBotResponse
	4,  // 23: codearena.v1.MatchService.GetMatchReplay:output_type -> codearena.v1.ReplayData
	6,  // 24: codearena.v1.MatchService.GetMatchHighlights:output_type -> codearena.v1.HighlightsData
	14, // 25: codearena.v1.SimulationService.StartSimulation:output_type -> codearena.v1.SimulationResponse
	14, // 26: codearena.v1.SimulationService.StopSimulation:output_type -> codearena.v1.SimulationResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_arena_proto_init() }
func file_arena_proto_init() {
	if File_arena_proto != nil {
		return
	}
	file_bot_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arena_proto_rawDesc), len(file_arena_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_arena_proto_goTypes,
		DependencyIndexes: file_arena_proto_depIdxs,
		MessageInfos:      file_arena_proto_msgTypes,
	}.Build()
	File_arena_proto = out.File
	file_arena_proto_goTypes = nil
	file_arena_proto_depIdxs = nil
}
