// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: arena.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchService_CreateMatch_FullMethodName        = "/codearena.v1.MatchService/CreateMatch"
	MatchService_ListActiveMatches_FullMethodName  = "/codearena.v1.MatchService/ListActiveMatches"
	MatchService_ListMatches_FullMethodName        = "/codearena.v1.MatchService/ListMatches"
	MatchService_WatchMatch_FullMethodName         = "/codearena.v1.MatchService/WatchMatch"
	MatchService_RegisterBot_FullMethodName        = "/codearena.v1.MatchService/RegisterBot"
	MatchService_GetMatchReplay_FullMethodName     = "/codearena.v1.MatchService/GetMatchReplay"
	MatchService_GetMatchHighlights_FullMethodName = "/codearena.v1.MatchService/GetMatchHighlights"
)

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchServiceClient interface {
	CreateMatch(ctx context.Context, in *ArenaConfig, opts ...grpc.CallOption) (*MatchResponse, error)
	ListActiveMatches(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MatchList, error)
	ListMatches(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MatchList, error)
	WatchMatch(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldState], error)
	RegisterBot(ctx context.Context, in *RegisterBotRequest, opts ...grpc.CallOption) (*RegisterBotResponse, error)
	GetMatchReplay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayData, error)
	GetMatchHighlights(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*HighlightsData, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) CreateMatch(ctx context.Context, in *ArenaConfig, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, MatchService_CreateMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) ListActiveMatches(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MatchList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchList)
	err := c.cc.Invoke(ctx, MatchService_ListActiveMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) ListMatches(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MatchList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchList)
	err := c.cc.Invoke(ctx, MatchService_ListMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) WatchMatch(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchService_ServiceDesc.Streams[0], MatchService_WatchMatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MatchRequest, WorldState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchService_WatchMatchClient = grpc.ServerStreamingClient[WorldState]

func (c *matchServiceClient) RegisterBot(ctx context.Context, in *RegisterBotRequest, opts ...grpc.CallOption) (*RegisterBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBotResponse)
	err := c.cc.Invoke(ctx, MatchService_RegisterBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetMatchReplay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayData)
	err := c.cc.Invoke(ctx, MatchService_GetMatchReplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetMatchHighlights(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*HighlightsData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HighlightsData)
	err := c.cc.Invoke(ctx, MatchService_GetMatchHighlights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility.
type MatchServiceServer interface {
	CreateMatch(context.Context, *ArenaConfig) (*MatchResponse, error)
	ListActiveMatches(context.Context, *Empty) (*MatchList, error)
	ListMatches(context.Context, *Empty) (*MatchList, error)
	WatchMatch(*MatchRequest, grpc.ServerStreamingServer[WorldState]) error
	RegisterBot(context.Context, *RegisterBotRequest) (*RegisterBotResponse, error)
	GetMatchReplay(context.Context, *ReplayRequest) (*ReplayData, error)
	GetMatchHighlights(context.Context, *ReplayRequest) (*HighlightsData, error)
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchServiceServer struct{}

func (UnimplementedMatchServiceServer) CreateMatch(context.Context, *ArenaConfig) (*MatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMatch not implemented")
}
func (UnimplementedMatchServiceServer) ListActiveMatches(context.Context, *Empty) (*MatchList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveMatches not implemented")
}
func (UnimplementedMatchServiceServer) ListMatches(context.Context, *Empty) (*MatchList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMatches not implemented")
}
func (UnimplementedMatchServiceServer) WatchMatch(*MatchRequest, grpc.ServerStreamingServer[WorldState]) error {
	return status.Error(codes.Unimplemented, "method WatchMatch not implemented")
}
func (UnimplementedMatchServiceServer) RegisterBot(context.Context, *RegisterBotRequest) (*RegisterBotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBot not implemented")
}
func (UnimplementedMatchServiceServer) GetMatchReplay(context.Context, *ReplayRequest) (*ReplayData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchReplay not implemented")
}
func (UnimplementedMatchServiceServer) GetMatchHighlights(context.Context, *ReplayRequest) (*HighlightsData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchHighlights not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}
func (UnimplementedMatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_CreateMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).CreateMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_CreateMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).CreateMatch(ctx, req.(*ArenaConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_ListActiveMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).ListActiveMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_ListActiveMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).ListActiveMatches(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_ListMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).ListMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_ListMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).ListMatches(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_WatchMatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchServiceServer).WatchMatch(m, &grpc.GenericServerStream[MatchRequest, WorldState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchService_WatchMatchServer = grpc.ServerStreamingServer[WorldState]

func _MatchService_RegisterBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).RegisterBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_RegisterBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).RegisterBot(ctx, req.(*RegisterBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetMatchReplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatchReplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetMatchReplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatchReplay(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetMatchHighlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatchHighlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetMatchHighlights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatchHighlights(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codearena.v1.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMatch",
			Handler:    _MatchService_CreateMatch_Handler,
		},
		{
			MethodName: "ListActiveMatches",
			Handler:    _MatchService_ListActiveMatches_Handler,
		},
		{
			MethodName: "ListMatches",
			Handler:    _MatchService_ListMatches_Handler,
		},
		{
			MethodName: "RegisterBot",
			Handler:    _MatchService_RegisterBot_Handler,
		},
		{
			MethodName: "GetMatchReplay",
			Handler:    _MatchService_GetMatchReplay_Handler,
		},
		{
			MethodName: "GetMatchHighlights",
			Handler:    _MatchService_GetMatchHighlights_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMatch",
			Handler:       _MatchService_WatchMatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arena.proto",
}

const (
	SimulationService_StartSimulation_FullMethodName = "/codearena.v1.SimulationService/StartSimulation"
	SimulationService_StopSimulation_FullMethodName  = "/codearena.v1.SimulationService/StopSimulation"
)

// SimulationServiceClient is the client API for SimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulationServiceClient interface {
	// External control for starting/stopping the engine
	StartSimulation(ctx context.Context, in *ArenaConfig, opts ...grpc.CallOption) (*SimulationResponse, error)
	StopSimulation(ctx context.Context, in *StopSimulationRequest, opts ...grpc.CallOption) (*SimulationResponse, error)
}

type simulationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationServiceClient(cc grpc.ClientConnInterface) SimulationServiceClient {
	return &simulationServiceClient{cc}
}

func (c *simulationServiceClient) StartSimulation(ctx context.Context, in *ArenaConfig, opts ...grpc.CallOption) (*SimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_StartSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) StopSimulation(ctx context.Context, in *StopSimulationRequest, opts ...grpc.CallOption) (*SimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_StopSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationServiceServer is the server API for SimulationService service.
// All implementations must embed UnimplementedSimulationServiceServer
// for forward compatibility.
type SimulationServiceServer interface {
	// External control for starting/stopping the engine
	StartSimulation(context.Context, *ArenaConfig) (*SimulationResponse, error)
	StopSimulation(context.Context, *StopSimulationRequest) (*SimulationResponse, error)
	mustEmbedUnimplementedSimulationServiceServer()
}

// UnimplementedSimulationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulationServiceServer struct{}

func (UnimplementedSimulationServiceServer) StartSimulation(context.Context, *ArenaConfig) (*SimulationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) StopSimulation(context.Context, *StopSimulationRequest) (*SimulationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) mustEmbedUnimplementedSimulationServiceServer() {}
func (UnimplementedSimulationServiceServer) testEmbeddedByValue()                           {}

// UnsafeSimulationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationServiceServer will
// result in compilation errors.
type UnsafeSimulationServiceServer interface {
	mustEmbedUnimplementedSimulationServiceServer()
}

func RegisterSimulationServiceServer(s grpc.ServiceRegistrar, srv SimulationServiceServer) {
	// If the following call panics, it indicates UnimplementedSimulationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulationService_ServiceDesc, srv)
}

func _SimulationService_StartSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).StartSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_StartSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).StartSimulation(ctx, req.(*ArenaConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_StopSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).StopSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_StopSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).StopSimulation(ctx, req.(*StopSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulationService_ServiceDesc is the grpc.ServiceDesc for SimulationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codearena.v1.SimulationService",
	HandlerType: (*SimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSimulation",
			Handler:    _SimulationService_StartSimulation_Handler,
		},
		{
			MethodName: "StopSimulation",
			Handler:    _SimulationService_StopSimulation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arena.proto",
}
