// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: bot_api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Global match status
type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNSPECIFIED MatchStatus = 0
	MatchStatus_WAITING                  MatchStatus = 1
	MatchStatus_RUNNING                  MatchStatus = 2
	MatchStatus_FINISHED                 MatchStatus = 3
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNSPECIFIED",
		1: "WAITING",
		2: "RUNNING",
		3: "FINISHED",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNSPECIFIED": 0,
		"WAITING":                  1,
		"RUNNING":                  2,
		"FINISHED":                 3,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bot_api_proto_enumTypes[0].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_bot_api_proto_enumTypes[0]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{0}
}

type PowerType int32

const (
	PowerType_POWER_NONE PowerType = 0
	PowerType_SHIELD     PowerType = 1
	PowerType_OVERCLOCK  PowerType = 2
	PowerType_STEALTH    PowerType = 3
)

// Enum value maps for PowerType.
var (
	PowerType_name = map[int32]string{
		0: "POWER_NONE",
		1: "SHIELD",
		2: "OVERCLOCK",
		3: "STEALTH",
	}
	PowerType_value = map[string]int32{
		"POWER_NONE": 0,
		"SHIELD":     1,
		"OVERCLOCK":  2,
		"STEALTH":    3,
	}
)

func (x PowerType) Enum() *PowerType {
	p := new(PowerType)
	*p = x
	return p
}

func (x PowerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerType) Descriptor() protoreflect.EnumDescriptor {
	return file_bot_api_proto_enumTypes[1].Descriptor()
}

func (PowerType) Type() protoreflect.EnumType {
	return &file_bot_api_proto_enumTypes[1]
}

func (x PowerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerType.Descriptor instead.
func (PowerType) EnumDescriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{1}
}

// Generic vector for 3D coordinates
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_bot_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// Information about a bot in the arena
type BotState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      *Vector3               `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Heading       float32                `protobuf:"fixed32,4,opt,name=heading,proto3" json:"heading,omitempty"`
	GunHeading    float32                `protobuf:"fixed32,5,opt,name=gun_heading,json=gunHeading,proto3" json:"gun_heading,omitempty"`
	RadarHeading  float32                `protobuf:"fixed32,6,opt,name=radar_heading,json=radarHeading,proto3" json:"radar_heading,omitempty"`
	Velocity      float32                `protobuf:"fixed32,7,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Energy        float32                `protobuf:"fixed32,8,opt,name=energy,proto3" json:"energy,omitempty"`
	Hull          float32                `protobuf:"fixed32,9,opt,name=hull,proto3" json:"hull,omitempty"`
	Heat          float32                `protobuf:"fixed32,10,opt,name=heat,proto3" json:"heat,omitempty"`
	ShieldHp      float32                `protobuf:"fixed32,11,opt,name=shield_hp,json=shieldHp,proto3" json:"shield_hp,omitempty"`                                                            // Remaining Shield points
	IsStealthed   bool                   `protobuf:"varint,12,opt,name=is_stealthed,json=isStealthed,proto3" json:"is_stealthed,omitempty"`                                                    // If active stealth module
	Cooldowns     map[string]int32       `protobuf:"bytes,13,rep,name=cooldowns,proto3" json:"cooldowns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Power-id to remaining ticks
	Class         string                 `protobuf:"bytes,14,opt,name=class,proto3" json:"class,omitempty"`                                                                                    // Tank, Scout, Sniper
	TeamId        string                 `protobuf:"bytes,15,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotState) Reset() {
	*x = BotState{}
	mi := &file_bot_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotState) ProtoMessage() {}

func (x *BotState) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotState.ProtoReflect.Descriptor instead.
func (*BotState) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{1}
}

func (x *BotState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BotState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BotState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BotState) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *BotState) GetGunHeading() float32 {
	if x != nil {
		return x.GunHeading
	}
	return 0
}

func (x *BotState) GetRadarHeading() float32 {
	if x != nil {
		return x.RadarHeading
	}
	return 0
}

func (x *BotState) GetVelocity() float32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *BotState) GetEnergy() float32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *BotState) GetHull() float32 {
	if x != nil {
		return x.Hull
	}
	return 0
}

func (x *BotState) GetHeat() float32 {
	if x != nil {
		return x.Heat
	}
	return 0
}

func (x *BotState) GetShieldHp() float32 {
	if x != nil {
		return x.ShieldHp
	}
	return 0
}

func (x *BotState) GetIsStealthed() bool {
	if x != nil {
		return x.IsStealthed
	}
	return false
}

func (x *BotState) GetCooldowns() map[string]int32 {
	if x != nil {
		return x.Cooldowns
	}
	return nil
}

func (x *BotState) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *BotState) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Event types emitted by the engine
type SimulationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tick  int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*SimulationEvent_HitByBullet
	//	*SimulationEvent_BulletHitTarget
	//	*SimulationEvent_HitWall
	//	*SimulationEvent_HitRobot
	//	*SimulationEvent_ZoneEntered
	//	*SimulationEvent_Death
	//	*SimulationEvent_MatchFinished
	Event         isSimulationEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationEvent) Reset() {
	*x = SimulationEvent{}
	mi := &file_bot_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent) ProtoMessage() {}

func (x *SimulationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent.ProtoReflect.Descriptor instead.
func (*SimulationEvent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationEvent) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *SimulationEvent) GetEvent() isSimulationEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SimulationEvent) GetHitByBullet() *HitByBulletEvent {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_HitByBullet); ok {
			return x.HitByBullet
		}
	}
	return nil
}

func (x *SimulationEvent) GetBulletHitTarget() *BulletHitTargetEvent {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_BulletHitTarget); ok {
			return x.BulletHitTarget
		}
	}
	return nil
}

func (x *SimulationEvent) GetHitWall() *HitWallEvent {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_HitWall); ok {
			return x.HitWall
		}
	}
	return nil
}

func (x *SimulationEvent) GetHitRobot() *HitRobotEvent {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_HitRobot); ok {
			return x.HitRobot
		}
	}
	return nil
}

func (x *SimulationEvent) GetZoneEntered() *ZoneEnteredEvent {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_ZoneEntered); ok {
			return x.ZoneEntered
		}
	}
	return nil
}

func (x *SimulationEvent) GetDeath() *DeathEvent {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_Death); ok {
			return x.Death
		}
	}
	return nil
}

func (x *SimulationEvent) GetMatchFinished() *MatchFinishedEvent {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_MatchFinished); ok {
			return x.MatchFinished
		}
	}
	return nil
}

type isSimulationEvent_Event interface {
	isSimulationEvent_Event()
}

type SimulationEvent_HitByBullet struct {
	HitByBullet *HitByBulletEvent `protobuf:"bytes,2,opt,name=hit_by_bullet,json=hitByBullet,proto3,oneof"`
}

type SimulationEvent_BulletHitTarget struct {
	BulletHitTarget *BulletHitTargetEvent `protobuf:"bytes,3,opt,name=bullet_hit_target,json=bulletHitTarget,proto3,oneof"`
}

type SimulationEvent_HitWall struct {
	HitWall *HitWallEvent `protobuf:"bytes,4,opt,name=hit_wall,json=hitWall,proto3,oneof"`
}

type SimulationEvent_HitRobot struct {
	HitRobot *HitRobotEvent `protobuf:"bytes,5,opt,name=hit_robot,json=hitRobot,proto3,oneof"`
}

type SimulationEvent_ZoneEntered struct {
	ZoneEntered *ZoneEnteredEvent `protobuf:"bytes,6,opt,name=zone_entered,json=zoneEntered,proto3,oneof"`
}

type SimulationEvent_Death struct {
	Death *DeathEvent `protobuf:"bytes,7,opt,name=death,proto3,oneof"`
}

type SimulationEvent_MatchFinished struct {
	MatchFinished *MatchFinishedEvent `protobuf:"bytes,8,opt,name=match_finished,json=matchFinished,proto3,oneof"`
}

func (*SimulationEvent_HitByBullet) isSimulationEvent_Event() {}

func (*SimulationEvent_BulletHitTarget) isSimulationEvent_Event() {}

func (*SimulationEvent_HitWall) isSimulationEvent_Event() {}

func (*SimulationEvent_HitRobot) isSimulationEvent_Event() {}

func (*SimulationEvent_ZoneEntered) isSimulationEvent_Event() {}

func (*SimulationEvent_Death) isSimulationEvent_Event() {}

func (*SimulationEvent_MatchFinished) isSimulationEvent_Event() {}

type HitByBulletEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VictimId      string                 `protobuf:"bytes,1,opt,name=victim_id,json=victimId,proto3" json:"victim_id,omitempty"`
	BulletId      string                 `protobuf:"bytes,2,opt,name=bullet_id,json=bulletId,proto3" json:"bullet_id,omitempty"`
	Damage        float32                `protobuf:"fixed32,3,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitByBulletEvent) Reset() {
	*x = HitByBulletEvent{}
	mi := &file_bot_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitByBulletEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitByBulletEvent) ProtoMessage() {}

func (x *HitByBulletEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitByBulletEvent.ProtoReflect.Descriptor instead.
func (*HitByBulletEvent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{3}
}

func (x *HitByBulletEvent) GetVictimId() string {
	if x != nil {
		return x.VictimId
	}
	return ""
}

func (x *HitByBulletEvent) GetBulletId() string {
	if x != nil {
		return x.BulletId
	}
	return ""
}

func (x *HitByBulletEvent) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type BulletHitTargetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BulletId      string                 `protobuf:"bytes,1,opt,name=bullet_id,json=bulletId,proto3" json:"bullet_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletHitTargetEvent) Reset() {
	*x = BulletHitTargetEvent{}
	mi := &file_bot_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletHitTargetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletHitTargetEvent) ProtoMessage() {}

func (x *BulletHitTargetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletHitTargetEvent.ProtoReflect.Descriptor instead.
func (*BulletHitTargetEvent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{4}
}

func (x *BulletHitTargetEvent) GetBulletId() string {
	if x != nil {
		return x.BulletId
	}
	return ""
}

func (x *BulletHitTargetEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type HitWallEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitWallEvent) Reset() {
	*x = HitWallEvent{}
	mi := &file_bot_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitWallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitWallEvent) ProtoMessage() {}

func (x *HitWallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitWallEvent.ProtoReflect.Descriptor instead.
func (*HitWallEvent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{5}
}

func (x *HitWallEvent) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type HitRobotEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	OtherId       string                 `protobuf:"bytes,2,opt,name=other_id,json=otherId,proto3" json:"other_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitRobotEvent) Reset() {
	*x = HitRobotEvent{}
	mi := &file_bot_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitRobotEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitRobotEvent) ProtoMessage() {}

func (x *HitRobotEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitRobotEvent.ProtoReflect.Descriptor instead.
func (*HitRobotEvent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{6}
}

func (x *HitRobotEvent) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *HitRobotEvent) GetOtherId() string {
	if x != nil {
		return x.OtherId
	}
	return ""
}

type ZoneEnteredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneEnteredEvent) Reset() {
	*x = ZoneEnteredEvent{}
	mi := &file_bot_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneEnteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneEnteredEvent) ProtoMessage() {}

func (x *ZoneEnteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneEnteredEvent.ProtoReflect.Descriptor instead.
func (*ZoneEnteredEvent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{7}
}

func (x *ZoneEnteredEvent) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *ZoneEnteredEvent) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ZoneEnteredEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeathEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	KillerId      string                 `protobuf:"bytes,2,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeathEvent) Reset() {
	*x = DeathEvent{}
	mi := &file_bot_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathEvent) ProtoMessage() {}

func (x *DeathEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathEvent.ProtoReflect.Descriptor instead.
func (*DeathEvent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{8}
}

func (x *DeathEvent) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *DeathEvent) GetKillerId() string {
	if x != nil {
		return x.KillerId
	}
	return ""
}

type MatchFinishedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerId      string                 `protobuf:"bytes,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFinishedEvent) Reset() {
	*x = MatchFinishedEvent{}
	mi := &file_bot_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFinishedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFinishedEvent) ProtoMessage() {}

func (x *MatchFinishedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFinishedEvent.ProtoReflect.Descriptor instead.
func (*MatchFinishedEvent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{9}
}

func (x *MatchFinishedEvent) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

type BulletState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Position      *Vector3               `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Heading       float32                `protobuf:"fixed32,4,opt,name=heading,proto3" json:"heading,omitempty"`
	Velocity      float32                `protobuf:"fixed32,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Power         float32                `protobuf:"fixed32,6,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletState) Reset() {
	*x = BulletState{}
	mi := &file_bot_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletState) ProtoMessage() {}

func (x *BulletState) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletState.ProtoReflect.Descriptor instead.
func (*BulletState) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{10}
}

func (x *BulletState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BulletState) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *BulletState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BulletState) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *BulletState) GetVelocity() float32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *BulletState) GetPower() float32 {
	if x != nil {
		return x.Power
	}
	return 0
}

type ZoneState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Radius        float32                `protobuf:"fixed32,3,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneState) Reset() {
	*x = ZoneState{}
	mi := &file_bot_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneState) ProtoMessage() {}

func (x *ZoneState) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneState.ProtoReflect.Descriptor instead.
func (*ZoneState) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{11}
}

func (x *ZoneState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ZoneState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ZoneState) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

// A single tick of the world
type WorldState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Status        MatchStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=codearena.v1.MatchStatus" json:"status,omitempty"`
	Bots          []*BotState            `protobuf:"bytes,3,rep,name=bots,proto3" json:"bots,omitempty"`
	Events        []*SimulationEvent     `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	Bullets       []*BulletState         `protobuf:"bytes,5,rep,name=bullets,proto3" json:"bullets,omitempty"`
	Zone          *ZoneState             `protobuf:"bytes,6,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldState) Reset() {
	*x = WorldState{}
	mi := &file_bot_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldState) ProtoMessage() {}

func (x *WorldState) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldState.ProtoReflect.Descriptor instead.
func (*WorldState) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{12}
}

func (x *WorldState) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldState) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

func (x *WorldState) GetBots() []*BotState {
	if x != nil {
		return x.Bots
	}
	return nil
}

func (x *WorldState) GetEvents() []*SimulationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *WorldState) GetBullets() []*BulletState {
	if x != nil {
		return x.Bullets
	}
	return nil
}

func (x *WorldState) GetZone() *ZoneState {
	if x != nil {
		return x.Zone
	}
	return nil
}

// Command intent from a bot for the next tick
type BotIntent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MoveDistance     float32                `protobuf:"fixed32,1,opt,name=move_distance,json=moveDistance,proto3" json:"move_distance,omitempty"` // + forward, - backward
	TurnDegrees      float32                `protobuf:"fixed32,2,opt,name=turn_degrees,json=turnDegrees,proto3" json:"turn_degrees,omitempty"`    // rotation
	GunTurnDegrees   float32                `protobuf:"fixed32,3,opt,name=gun_turn_degrees,json=gunTurnDegrees,proto3" json:"gun_turn_degrees,omitempty"`
	RadarTurnDegrees float32                `protobuf:"fixed32,4,opt,name=radar_turn_degrees,json=radarTurnDegrees,proto3" json:"radar_turn_degrees,omitempty"`
	FirePower        float32                `protobuf:"fixed32,5,opt,name=fire_power,json=firePower,proto3" json:"fire_power,omitempty"` // 0.1 to 3.0
	UsePower         PowerType              `protobuf:"varint,6,opt,name=use_power,json=usePower,proto3,enum=codearena.v1.PowerType" json:"use_power,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BotIntent) Reset() {
	*x = BotIntent{}
	mi := &file_bot_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotIntent) ProtoMessage() {}

func (x *BotIntent) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotIntent.ProtoReflect.Descriptor instead.
func (*BotIntent) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{13}
}

func (x *BotIntent) GetMoveDistance() float32 {
	if x != nil {
		return x.MoveDistance
	}
	return 0
}

func (x *BotIntent) GetTurnDegrees() float32 {
	if x != nil {
		return x.TurnDegrees
	}
	return 0
}

func (x *BotIntent) GetGunTurnDegrees() float32 {
	if x != nil {
		return x.GunTurnDegrees
	}
	return 0
}

func (x *BotIntent) GetRadarTurnDegrees() float32 {
	if x != nil {
		return x.RadarTurnDegrees
	}
	return 0
}

func (x *BotIntent) GetFirePower() float32 {
	if x != nil {
		return x.FirePower
	}
	return 0
}

func (x *BotIntent) GetUsePower() PowerType {
	if x != nil {
		return x.UsePower
	}
	return PowerType_POWER_NONE
}

var File_bot_api_proto protoreflect.FileDescriptor

const file_bot_api_proto_rawDesc = "" +
	"\n" +
	"\rbot_api.proto\x12\fcodearena.v1\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\x8f\x04\n" +
	"\bBotState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\bposition\x18\x03 \x01(\v2\x15.codearena.v1.Vector3R\bposition\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x02R\aheading\x12\x1f\n" +
	"\vgun_heading\x18\x05 \x01(\x02R\n" +
	"gunHeading\x12#\n" +
	"\rradar_heading\x18\x06 \x01(\x02R\fradarHeading\x12\x1a\n" +
	"\bvelocity\x18\a \x01(\x02R\bvelocity\x12\x16\n" +
	"\x06energy\x18\b \x01(\x02R\x06energy\x12\x12\n" +
	"\x04hull\x18\t \x01(\x02R\x04hull\x12\x12\n" +
	"\x04heat\x18\n" +
	" \x01(\x02R\x04heat\x12\x1b\n" +
	"\tshield_hp\x18\v \x01(\x02R\bshieldHp\x12!\n" +
	"\fis_stealthed\x18\f \x01(\bR\visStealthed\x12C\n" +
	"\tcooldowns\x18\r \x03(\v2%.codearena.v1.BotState.CooldownsEntryR\tcooldowns\x12\x14\n" +
	"\x05class\x18\x0e \x01(\tR\x05class\x12\x17\n" +
	"\ateam_id\x18\x0f \x01(\tR\x06teamId\x1a<\n" +
	"\x0eCooldownsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xfd\x03\n" +
	"\x0fSimulationEvent\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12D\n" +
	"\rhit_by_bullet\x18\x02 \x01(\v2\x1e.codearena.v1.HitByBulletEventH\x00R\vhitByBullet\x12P\n" +
	"\x11bullet_hit_target\x18\x03 \x01(\v2\".codearena.v1.BulletHitTargetEventH\x00R\x0fbulletHitTarget\x127\n" +
	"\bhit_wall\x18\x04 \x01(\v2\x1a.codearena.v1.HitWallEventH\x00R\ahitWall\x12:\n" +
	"\thit_robot\x18\x05 \x01(\v2\x1b.codearena.v1.HitRobotEventH\x00R\bhitRobot\x12C\n" +
	"\fzone_entered\x18\x06 \x01(\v2\x1e.codearena.v1.ZoneEnteredEventH\x00R\vzoneEntered\x120\n" +
	"\x05death\x18\a \x01(\v2\x18.codearena.v1.DeathEventH\x00R\x05death\x12I\n" +
	"\x0ematch_finished\x18\b \x01(\v2 .codearena.v1.MatchFinishedEventH\x00R\rmatchFinishedB\a\n" +
	"\x05event\"d\n" +
	"\x10HitByBulletEvent\x12\x1b\n" +
	"\tvictim_id\x18\x01 \x01(\tR\bvictimId\x12\x1b\n" +
	"\tbullet_id\x18\x02 \x01(\tR\bbulletId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x02R\x06damage\"P\n" +
	"\x14BulletHitTargetEvent\x12\x1b\n" +
	"\tbullet_id\x18\x01 \x01(\tR\bbulletId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\"%\n" +
	"\fHitWallEvent\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"A\n" +
	"\rHitRobotEvent\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x19\n" +
	"\bother_id\x18\x02 \x01(\tR\aotherId\"V\n" +
	"\x10ZoneEnteredEvent\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"@\n" +
	"\n" +
	"DeathEvent\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x1b\n" +
	"\tkiller_id\x18\x02 \x01(\tR\bkillerId\"1\n" +
	"\x12MatchFinishedEvent\x12\x1b\n" +
	"\twinner_id\x18\x01 \x01(\tR\bwinnerId\"\xb7\x01\n" +
	"\vBulletState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x121\n" +
	"\bposition\x18\x03 \x01(\v2\x15.codearena.v1.Vector3R\bposition\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x02R\aheading\x12\x1a\n" +
	"\bvelocity\x18\x05 \x01(\x02R\bvelocity\x12\x14\n" +
	"\x05power\x18\x06 \x01(\x02R\x05power\"?\n" +
	"\tZoneState\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x02R\x06radius\"\x98\x02\n" +
	"\n" +
	"WorldState\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.codearena.v1.MatchStatusR\x06status\x12*\n" +
	"\x04bots\x18\x03 \x03(\v2\x16.codearena.v1.BotStateR\x04bots\x125\n" +
	"\x06events\x18\x04 \x03(\v2\x1d.codearena.v1.SimulationEventR\x06events\x123\n" +
	"\abullets\x18\x05 \x03(\v2\x19.codearena.v1.BulletStateR\abullets\x12+\n" +
	"\x04zone\x18\x06 \x01(\v2\x17.codearena.v1.ZoneStateR\x04zone\"\x80\x02\n" +
	"\tBotIntent\x12#\n" +
	"\rmove_distance\x18\x01 \x01(\x02R\fmoveDistance\x12!\n" +
	"\fturn_degrees\x18\x02 \x01(\x02R\vturnDegrees\x12(\n" +
	"\x10gun_turn_degrees\x18\x03 \x01(\x02R\x0egunTurnDegrees\x12,\n" +
	"\x12radar_turn_degrees\x18\x04 \x01(\x02R\x10radarTurnDegrees\x12\x1d\n" +
	"\n" +
	"fire_power\x18\x05 \x01(\x02R\tfirePower\x124\n" +
	"\tuse_power\x18\x06 \x01(\x0e2\x17.codearena.v1.PowerTypeR\busePower*S\n" +
	"\vMatchStatus\x12\x1c\n" +
	"\x18MATCH_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aWAITING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\f\n" +
	"\bFINISHED\x10\x03*C\n" +
	"\tPowerType\x12\x0e\n" +
	"\n" +
	"POWER_NONE\x10\x00\x12\n" +
	"\n" +
	"\x06SHIELD\x10\x01\x12\r\n" +
	"\tOVERCLOCK\x10\x02\x12\v\n" +
	"\aSTEALTH\x10\x032N\n" +
	"\n" +
	"BotService\x12@\n" +
	"\aConnect\x12\x17.codearena.v1.BotIntent\x1a\x18.codearena.v1.WorldState(\x010\x01B9Z7github.com/codearena-platform/codearena-core/pkg/api/v1b\x06proto3"

var (
	file_bot_api_proto_rawDescOnce sync.Once
	file_bot_api_proto_rawDescData []byte
)

func file_bot_api_proto_rawDescGZIP() []byte {
	file_bot_api_proto_rawDescOnce.Do(func() {
		file_bot_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_api_proto_rawDesc), len(file_bot_api_proto_rawDesc)))
	})
	return file_bot_api_proto_rawDescData
}

var file_bot_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bot_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_bot_api_proto_goTypes = []any{
	(MatchStatus)(0),             // 0: codearena.v1.MatchStatus
	(PowerType)(0),               // 1: codearena.v1.PowerType
	(*Vector3)(nil),              // 2: codearena.v1.Vector3
	(*BotState)(nil),             // 3: codearena.v1.BotState
	(*SimulationEvent)(nil),      // 4: codearena.v1.SimulationEvent
	(*HitByBulletEvent)(nil),     // 5: codearena.v1.HitByBulletEvent
	(*BulletHitTargetEvent)(nil), // 6: codearena.v1.BulletHitTargetEvent
	(*HitWallEvent)(nil),         // 7: codearena.v1.HitWallEvent
	(*HitRobotEvent)(nil),        // 8: codearena.v1.HitRobotEvent
	(*ZoneEnteredEvent)(nil),     // 9: codearena.v1.ZoneEnteredEvent
	(*DeathEvent)(nil),           // 10: codearena.v1.DeathEvent
	(*MatchFinishedEvent)(nil),   // 11: codearena.v1.MatchFinishedEvent
	(*BulletState)(nil),          // 12: codearena.v1.BulletState
	(*ZoneState)(nil),            // 13: codearena.v1.ZoneState
	(*WorldState)(nil),           // 14: codearena.v1.WorldState
	(*BotIntent)(nil),            // 15: codearena.v1.BotIntent
	nil,                          // 16: codearena.v1.BotState.CooldownsEntry
}
var file_bot_api_proto_depIdxs = []int32{
	2,  // 0: codearena.v1.BotState.position:type_name -> codearena.v1.Vector3
	16, // 1: codearena.v1.BotState.cooldowns:type_name -> codearena.v1.BotState.CooldownsEntry
	5,  // 2: codearena.v1.SimulationEvent.hit_by_bullet:type_name -> codearena.v1.HitByBulletEvent
	6,  // 3: codearena.v1.SimulationEvent.bullet_hit_target:type_name -> codearena.v1.BulletHitTargetEvent
	7,  // 4: codearena.v1.SimulationEvent.hit_wall:type_name -> codearena.v1.HitWallEvent
	8,  // 5: codearena.v1.SimulationEvent.hit_robot:type_name -> codearena.v1.HitRobotEvent
	9,  // 6: codearena.v1.SimulationEvent.zone_entered:type_name -> codearena.v1.ZoneEnteredEvent
	10, // 7: codearena.v1.SimulationEvent.death:type_name -> codearena.v1.DeathEvent
	11, // 8: codearena.v1.SimulationEvent.match_finished:type_name -> codearena.v1.MatchFinishedEvent
	2,  // 9: codearena.v1.BulletState.position:type_name -> codearena.v1.Vector3
	0,  // 10: codearena.v1.WorldState.status:type_name -> codearena.v1.MatchStatus
	3,  // 11: codearena.v1.WorldState.bots:type_name -> codearena.v1.BotState
	4,  // 12: codearena.v1.WorldState.events:type_name -> codearena.v1.SimulationEvent
	12, // 13: codearena.v1.WorldState.bullets:type_name -> codearena.v1.BulletState
	13, // 14: codearena.v1.WorldState.zone:type_name -> codearena.v1.ZoneState
	1,  // 15: codearena.v1.BotIntent.use_power:type_name -> codearena.v1.PowerType
	15, // 16: codearena.v1.BotService.Connect:input_type -> codearena.v1.BotIntent
	14, // 17: codearena.v1.BotService.Connect:output_type -> codearena.v1.WorldState
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_bot_api_proto_init() }
func file_bot_api_proto_init() {
	if File_bot_api_proto != nil {
		return
	}
	file_bot_api_proto_msgTypes[2].OneofWrappers = []any{
		(*SimulationEvent_HitByBullet)(nil),
		(*SimulationEvent_BulletHitTarget)(nil),
		(*SimulationEvent_HitWall)(nil),
		(*SimulationEvent_HitRobot)(nil),
		(*SimulationEvent_ZoneEntered)(nil),
		(*SimulationEvent_Death)(nil),
		(*SimulationEvent_MatchFinished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_api_proto_rawDesc), len(file_bot_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_api_proto_goTypes,
		DependencyIndexes: file_bot_api_proto_depIdxs,
		EnumInfos:         file_bot_api_proto_enumTypes,
		MessageInfos:      file_bot_api_proto_msgTypes,
	}.Build()
	File_bot_api_proto = out.File
	file_bot_api_proto_goTypes = nil
	file_bot_api_proto_depIdxs = nil
}
