// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: runtime.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeService_StartBot_FullMethodName        = "/codearena.v1.RuntimeService/StartBot"
	RuntimeService_StopBot_FullMethodName         = "/codearena.v1.RuntimeService/StopBot"
	RuntimeService_GetRuntimeStats_FullMethodName = "/codearena.v1.RuntimeService/GetRuntimeStats"
)

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service specific to the Runtime environment (Sandboxing)
type RuntimeServiceClient interface {
	// Request to start a bot container/process
	StartBot(ctx context.Context, in *StartBotRequest, opts ...grpc.CallOption) (*StartBotResponse, error)
	// Request to stop a bot
	StopBot(ctx context.Context, in *StopBotRequest, opts ...grpc.CallOption) (*StopBotResponse, error)
	// Health check for runtime stats
	GetRuntimeStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RuntimeStats, error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) StartBot(ctx context.Context, in *StartBotRequest, opts ...grpc.CallOption) (*StartBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBotResponse)
	err := c.cc.Invoke(ctx, RuntimeService_StartBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) StopBot(ctx context.Context, in *StopBotRequest, opts ...grpc.CallOption) (*StopBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopBotResponse)
	err := c.cc.Invoke(ctx, RuntimeService_StopBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) GetRuntimeStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RuntimeStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeStats)
	err := c.cc.Invoke(ctx, RuntimeService_GetRuntimeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility.
//
// Service specific to the Runtime environment (Sandboxing)
type RuntimeServiceServer interface {
	// Request to start a bot container/process
	StartBot(context.Context, *StartBotRequest) (*StartBotResponse, error)
	// Request to stop a bot
	StopBot(context.Context, *StopBotRequest) (*StopBotResponse, error)
	// Health check for runtime stats
	GetRuntimeStats(context.Context, *Empty) (*RuntimeStats, error)
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServiceServer struct{}

func (UnimplementedRuntimeServiceServer) StartBot(context.Context, *StartBotRequest) (*StartBotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBot not implemented")
}
func (UnimplementedRuntimeServiceServer) StopBot(context.Context, *StopBotRequest) (*StopBotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopBot not implemented")
}
func (UnimplementedRuntimeServiceServer) GetRuntimeStats(context.Context, *Empty) (*RuntimeStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeStats not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}
func (UnimplementedRuntimeServiceServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeService_ServiceDesc, srv)
}

func _RuntimeService_StartBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).StartBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_StartBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).StartBot(ctx, req.(*StartBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_StopBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).StopBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_StopBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).StopBot(ctx, req.(*StopBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_GetRuntimeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GetRuntimeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GetRuntimeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GetRuntimeStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeService_ServiceDesc is the grpc.ServiceDesc for RuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codearena.v1.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartBot",
			Handler:    _RuntimeService_StartBot_Handler,
		},
		{
			MethodName: "StopBot",
			Handler:    _RuntimeService_StopBot_Handler,
		},
		{
			MethodName: "GetRuntimeStats",
			Handler:    _RuntimeService_GetRuntimeStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime.proto",
}
