// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: runtime.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartBotRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BotId           string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Image           string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`                                            // Docker image or runtime environment identifier
	SourceCode      string                 `protobuf:"bytes,3,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`                // Code to execute (if applicable)
	EnvironmentVars string                 `protobuf:"bytes,4,opt,name=environment_vars,json=environmentVars,proto3" json:"environment_vars,omitempty"` // JSON string of env vars
	MatchId         string                 `protobuf:"bytes,5,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	GameServerUrl   string                 `protobuf:"bytes,6,opt,name=game_server_url,json=gameServerUrl,proto3" json:"game_server_url,omitempty"` // Where the bot should connect to
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartBotRequest) Reset() {
	*x = StartBotRequest{}
	mi := &file_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBotRequest) ProtoMessage() {}

func (x *StartBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBotRequest.ProtoReflect.Descriptor instead.
func (*StartBotRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *StartBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *StartBotRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StartBotRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *StartBotRequest) GetEnvironmentVars() string {
	if x != nil {
		return x.EnvironmentVars
	}
	return ""
}

func (x *StartBotRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *StartBotRequest) GetGameServerUrl() string {
	if x != nil {
		return x.GameServerUrl
	}
	return ""
}

type StartBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Queued        bool                   `protobuf:"varint,4,opt,name=queued,proto3" json:"queued,omitempty"`
	QueuePosition int32                  `protobuf:"varint,5,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBotResponse) Reset() {
	*x = StartBotResponse{}
	mi := &file_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBotResponse) ProtoMessage() {}

func (x *StartBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBotResponse.ProtoReflect.Descriptor instead.
func (*StartBotResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *StartBotResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StartBotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartBotResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StartBotResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *StartBotResponse) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

type StopBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopBotRequest) Reset() {
	*x = StopBotRequest{}
	mi := &file_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBotRequest) ProtoMessage() {}

func (x *StopBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBotRequest.ProtoReflect.Descriptor instead.
func (*StopBotRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *StopBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *StopBotRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopBotResponse) Reset() {
	*x = StopBotResponse{}
	mi := &file_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBotResponse) ProtoMessage() {}

func (x *StopBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBotResponse.ProtoReflect.Descriptor instead.
func (*StopBotResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *StopBotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RuntimeStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActiveContainers int32                  `protobuf:"varint,1,opt,name=active_containers,json=activeContainers,proto3" json:"active_containers,omitempty"`
	MemoryUsageMb    int64                  `protobuf:"varint,2,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	CpuUsagePercent  float32                `protobuf:"fixed32,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuntimeStats) Reset() {
	*x = RuntimeStats{}
	mi := &file_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStats) ProtoMessage() {}

func (x *RuntimeStats) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStats.ProtoReflect.Descriptor instead.
func (*RuntimeStats) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeStats) GetActiveContainers() int32 {
	if x != nil {
		return x.ActiveContainers
	}
	return 0
}

func (x *RuntimeStats) GetMemoryUsageMb() int64 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *RuntimeStats) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

var File_runtime_proto protoreflect.FileDescriptor

const file_runtime_proto_rawDesc = "" +
	"\n" +
	"\rruntime.proto\x12\fcodearena.v1\x1a\rbot_api.proto\x1a\varena.proto\"\xcd\x01\n" +
	"\x0fStartBotRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1f\n" +
	"\vsource_code\x18\x03 \x01(\tR\n" +
	"sourceCode\x12)\n" +
	"\x10environment_vars\x18\x04 \x01(\tR\x0fenvironmentVars\x12\x19\n" +
	"\bmatch_id\x18\x05 \x01(\tR\amatchId\x12&\n" +
	"\x0fgame_server_url\x18\x06 \x01(\tR\rgameServerUrl\"\xb3\x01\n" +
	"\x10StartBotResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06queued\x18\x04 \x01(\bR\x06queued\x12%\n" +
	"\x0equeue_position\x18\x05 \x01(\x05R\rqueuePosition\"J\n" +
	"\x0eStopBotRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"+\n" +
	"\x0fStopBotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8f\x01\n" +
	"\fRuntimeStats\x12+\n" +
	"\x11active_containers\x18\x01 \x01(\x05R\x10activeContainers\x12&\n" +
	"\x0fmemory_usage_mb\x18\x02 \x01(\x03R\rmemoryUsageMb\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x02R\x0fcpuUsagePercent2\xe7\x01\n" +
	"\x0eRuntimeService\x12I\n" +
	"\bStartBot\x12\x1d.codearena.v1.StartBotRequest\x1a\x1e.codearena.v1.StartBotResponse\x12F\n" +
	"\aStopBot\x12\x1c.codearena.v1.StopBotRequest\x1a\x1d.codearena.v1.StopBotResponse\x12B\n" +
	"\x0fGetRuntimeStats\x12\x13.codearena.v1.Empty\x1a\x1a.codearena.v1.RuntimeStatsB9Z7github.com/codearena-platform/codearena-core/pkg/api/v1b\x06proto3"

var (
	file_runtime_proto_rawDescOnce sync.Once
	file_runtime_proto_rawDescData []byte
)

func file_runtime_proto_rawDescGZIP() []byte {
	file_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)))
	})
	return file_runtime_proto_rawDescData
}

var file_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_runtime_proto_goTypes = []any{
	(*StartBotRequest)(nil),  // 0: codearena.v1.StartBotRequest
	(*StartBotResponse)(nil), // 1: codearena.v1.StartBotResponse
	(*StopBotRequest)(nil),   // 2: codearena.v1.StopBotRequest
	(*StopBotResponse)(nil),  // 3: codearena.v1.StopBotResponse
	(*RuntimeStats)(nil),     // 4: codearena.v1.RuntimeStats
	(*Empty)(nil),            // 5: codearena.v1.Empty
}
var file_runtime_proto_depIdxs = []int32{
	0, // 0: codearena.v1.RuntimeService.StartBot:input_type -> codearena.v1.StartBotRequest
	2, // 1: codearena.v1.RuntimeService.StopBot:input_type -> codearena.v1.StopBotRequest
	5, // 2: codearena.v1.RuntimeService.GetRuntimeStats:input_type -> codearena.v1.Empty
	1, // 3: codearena.v1.RuntimeService.StartBot:output_type -> codearena.v1.StartBotResponse
	3, // 4: codearena.v1.RuntimeService.StopBot:output_type -> codearena.v1.StopBotResponse
	4, // 5: codearena.v1.RuntimeService.GetRuntimeStats:output_type -> codearena.v1.RuntimeStats
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_proto_init() }
func file_runtime_proto_init() {
	if File_runtime_proto != nil {
		return
	}
	file_bot_api_proto_init()
	file_arena_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_proto_depIdxs,
		MessageInfos:      file_runtime_proto_msgTypes,
	}.Build()
	File_runtime_proto = out.File
	file_runtime_proto_goTypes = nil
	file_runtime_proto_depIdxs = nil
}
