FROM golang:1.24-alpine

RUN apk add --no-cache protobuf-dev protoc git

# Install gRPC and OpenAPI plugins
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && \
    go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest

WORKDIR /workspace
ENTRYPOINT ["protoc"]
